INSERT INTO TB_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL) VALUES (1, 'Bruno', 'bruno', '1234','brunogrzegork@gmail.com');

ALTER SEQUENCE TB_USUARIO_ID_SEQ RESTART WITH 2;

INSERT INTO TB_PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO TB_PERFIL (ID, DESCRICAO) VALUES (2, 'Gerente');
INSERT INTO TB_PERFIL (ID, DESCRICAO) VALUES (3, 'Cliente');

ALTER SEQUENCE TB_PERFIL_SEQ RESTART WITH 4;

INSERT INTO TB_RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuário', 'usuario');
INSERT INTO TB_RECURSO (ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO TB_RECURSO (ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE TB_RECURSO_SEQ RESTART WITH 4;