INSERT INTO tb_usuario(ID,NOME, LOGIN, SENHA, EMAIL) VALUES (1,'nome','login','senha','email');

ALTER SEQUENCE TB_USUARIO_ID_SEQ RESTART WITH 2;

INSERT INTO tb_perfil(ID,DESCRICAO) VALUES(1,'descricao');

ALTER SEQUENCE TB_PERFIL_SEQ RESTART WITH 2;


